### ISSUE TITLE
Request header 파싱 오류

### ISSUE THREAD

**Issue by OverRaddit** [OverRaddit/WebServ#4]
Host: localhost:3000
이 부분을 파싱할 때, key-value를 자르는 기준이 ":" 문자라서 그런지
key : Host, value : localhost000 으로 나온다.
![스크린샷 2022-08-31 오후 3 23 26](https://user-images.githubusercontent.com/30787477/187608145-65a8745a-f23d-42d6-bbf2-1d2f274e0e0a.png)

**Comment by Rob-Yoo** [comment]
확인

**Comment by OverRaddit** [comment]
수정완료
